from tkinter import *

root = Tk()
btn1 = Button(root, text="1", font=('', 40))
btn2 = Button(root, text="2", font=('', 40))
btn3 = Button(root, text="3", font=('', 40))
btn4 = Button(root, text="4", font=('', 40))
btn5 = Button(root, text="5", font=('', 40))
btn6 = Button(root, text="6", font=('', 40))
btn7 = Button(root, text="7", font=('', 40))
btn8 = Button(root, text="8", font=('', 40))
btn9 = Button(root, text="9", font=('', 40))
btnplus = Button(root, text="+", font=('', 40))
btnclear = Button(root, text="Clear", font=('', 40))
btnequal = Button(root, text="=", font=('', 40))
btn1.grid(row=1, column=1, sticky='news')
btnclear.grid(row=1, column=2, sticky='news')
btn5.grid(row=2, column=1, sticky='news')
btn4.grid(row=2, column=2, sticky='news')
btnplus.grid(row=3, column=1, columnspan=2, sticky='news')
btn8.grid(row=4, column=1, sticky='news')
btn9.grid(row=4, column=2, sticky='news')
btn3.grid(row=1, rowspan=2, column=3, sticky='news')
btn6.grid(row=1, column=4, sticky='news')
btn7.grid(row=2, column=4, sticky='news')
btnequal.grid(row=1, column=5, rowspan=4, sticky='news')
btn2.grid(row=3, column=3, rowspan=2, columnspan=2, sticky='news')

mainloop()
