from tkinter import *
root = Tk()
l_q1 = Label(root, text = "6*5?")
a1 = IntVar(root)
a1.set(0)
a2 = IntVar(root)
a2.set(0)
rb_q1 = Radiobutton(root, text="50", value=1, variable=a1, selectimage=)
rb_q2 = Radiobutton(root, text="30", value=2, variable=a1)
rb_q3 = Radiobutton(root, text="60", value=3, variable=a1)
rb_q4 = Radiobutton(root, text="20", value=4, variable=a1)
l_q1.grid(row=1, column=1)
rb_q1.grid(row=2, column=1)
rb_q2.grid(row=2, column=2)
rb_q3.grid(row=2, column=3)
rb_q4.grid(row=2, column=4)
l_q2 = Label(root, text = "Capital of Iran?")
rb_q21 = Radiobutton(root, text="Karaj", value=1, variable=a2)
rb_q22 = Radiobutton(root, text="Rasht", value=2, variable=a2)
rb_q23 = Radiobutton(root, text="Anzali", value=3, variable=a2)
rb_q24 = Radiobutton(root, text="Tehran", value=4, variable=a2)
l_q2.grid(row=3, column=1)
rb_q21.grid(row=4, column=1)
rb_q22.grid(row=4, column=2)
rb_q23.grid(row=4, column=3)
rb_q24.grid(row=4, column=4)

mainloop()